### PR TITLE
Add WebRequest to HttpErrorAttributesAdaptor

### PR DESCRIPTION
**Pull request by bfkelsey**
- This will allow returing more information to the user based on the request.
- Specifically the request uri

Signed-off-by: Ben Kelsey <bfkelsey@gmail.com>

### CODE REVIEW

**Comment by alimate** [comment]
We could also keep the adapter intact and encapsulate request information (and other possible metadata) in the `HttpError` data class. What do you think @bfkelsey?

**Comment by alimate** [comment]
@bfkelsey Sorry It took me so long to respond, I had a crazy week!

**Comment by bfkelsey** [comment]
@alimate That is a good idea. That makes it so the change isn't breaking.

**Comment by alimate** [comment]
Since we should somehow encapsulate the reactive request, too, then I'm closing this PR in favor of another upcoming one. Thanks 🙏

**Pull request closed without merging**
